---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.1
  - name: centos-6.6
  
suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        config: &defaut-config
          datacenter: FortMeade
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
  - name: source
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        config: *default-config
        service:
          install_method: source
  - name: package
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        service:
          install_method: package
        config: *default-config
    excludes:
      - centos-7.1
      - centos-6.6
