---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.1
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        config:
          datacenter: FortMeade
          bind_interface: eth0
          advertise_interface: eth0
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
  - name: source
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        service:
          install_method: source
  - name: package
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        service:
          install_method: package
        config:
          datacenter: FortMeade
          bind_interface: eth0
          advertise_interface: eth0
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
    excludes:
      - centos-7.0
      - centos-6.5
